package com.uc;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.LinkedList;

import com.uc.interpretor.AppDomain;
import com.uc.interpretor.DomainBuffer;
import com.uc.interpretor.Function;
import com.uc.interpretor.Interpretor;
import com.uc.interpretor.Module;
import com.uc.interpretor.NativeFunction;
import com.uc.parser.FunctionData;
import com.uc.parser.ParseException;
import com.uc.parser.Parser;
import com.uc.parser.QName;

public class TestParser {

	private static String src = "method\n"
			+ "name null\n"
			+ "param Qname(PackageNamespace(\"\"),\"int\")\n"
			+ "param Qname(PackageNamespace(\"\"),\"String\")\n"
			+ "param Qname(PackageNamespace(\"\"),\"uint\")\n"
			+ "returns Qname(PackageNamespace(\"\"),\"String\")\n"
			+ "\n"
			+ "body\n"
			+ "maxstack 50\n"
			+ "localcount 45\n"
			+ "initscopedepth 0\n"
			+ "maxscopedepth 2\n"
			+ "\n"
			+ "code\n"
			+ "getlocal_0\n"
			+ "dup\n"
			+ "pushscope\n"
			+ "pushscope\n"
			+ "pushbyte 0\n"
			+ "setlocal 11\n"
			+ "pushnull\n"
			+ "setlocal 4\n"
			+ "pushbyte 0\n"
			+ "setlocal 44\n"
			+ "pushbyte 0\n"
			+ "setlocal 29\n"
			+ "pushbyte 0\n"
			+ "setlocal 37\n"
			+ "pushbyte 0\n"
			+ "setlocal 39\n"
			+ "pushnan\n"
			+ "setlocal 17\n"
			+ "pushbyte 0\n"
			+ "setlocal 42\n"
			+ "pushbyte 0\n"
			+ "setlocal 26\n"
			+ "pushbyte 0\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "setlocal 36\n"
			+ "pushbyte 0\n"
			+ "setlocal 38\n"
			+ "pushbyte 0\n"
			+ "setlocal 34\n"
			+ "pushbyte 0\n"
			+ "setlocal 28\n"
			+ "pushbyte 0\n"
			+ "setlocal 18\n"
			+ "pushbyte 0\n"
			+ "setlocal 27\n"
			+ "pushbyte 0\n"
			+ "setlocal 43\n"
			+ "pushbyte 0\n"
			+ "setlocal 32\n"
			+ "pushbyte 0\n"
			+ "setlocal 23\n"
			+ "pushbyte 0\n"
			+ "setlocal 24\n"
			+ "pushbyte 0\n"
			+ "setlocal 30\n"
			+ "pushbyte 0\n"
			+ "setlocal 8\n"
			+ "pushbyte 0\n"
			+ "setlocal 5\n"
			+ "pushbyte 0\n"
			+ "setlocal 20\n"
			+ "pushbyte 0\n"
			+ "setlocal 16\n"
			+ "pushbyte 0\n"
			+ "setlocal 14\n"
			+ "pushbyte 0\n"
			+ "setlocal 40\n"
			+ "pushbyte 0\n"
			+ "setlocal 25\n"
			+ "pushbyte 0\n"
			+ "setlocal 19\n"
			+ "pushbyte 0\n"
			+ "setlocal 35\n"
			+ "pushbyte 0\n"
			+ "setlocal 33\n"
			+ "pushbyte 0\n"
			+ "setlocal 15\n"
			+ "pushbyte 0\n"
			+ "setlocal 12\n"
			+ "pushbyte 0\n"
			+ "setlocal 13\n"
			+ "pushbyte 0\n"
			+ "setlocal 9\n"
			+ "pushbyte 0\n"
			+ "setlocal 10\n"
			+ "pushbyte 0\n"
			+ "setlocal 6\n"
			+ "pushbyte 0\n"
			+ "setlocal 41\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 7\n"
			+ "setlocal 11\n"
			+ "getlocal 7\n"
			+ "pushshort 3088\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 7\n"
			+ "getlocal_1\n"
			+ "setlocal 22\n"
			+ "getlocal 7\n"
			+ "pushbyte -16\n"
			+ "bitand\n"
			+ "findproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "swap\n"
			+ "setproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"CModule\")\n"
			+ "getlocal_2\n"
			+ "callproperty Qname(PackageNamespace(\"\"),\"mallocString\") 1\n"
			+ "convert_i\n"
			+ "setlocal 44\n"
			+ "getlocal_3\n"
			+ "convert_d\n"
			+ "setlocal 17\n"
			+ "getlocal 7\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 7\n"
			+ "pushshort 1024\n"
			+ "getlocal 7\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "si32\n"
			+ "pushbyte 0\n"
			+ "dup\n"
			+ "setlocal 43\n"
			+ "getlocal 7\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 11\n"
			+ "pushshort 3088\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 42\n"
			+ "getlocal 7\n"
			+ "si32\n"
			+ "getlocal 7\n"
			+ "findproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "swap\n"
			+ "setproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "findpropstrict Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"Fmemset\")\n"
			+ "callpropvoid Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"Fmemset\") 0\n"
			+ "getlocal 7\n"
			+ "pushbyte 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 7\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 7\n"
			+ "pushshort 1024\n"
			+ "getlocal 7\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 43\n"
			+ "getlocal 7\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 11\n"
			+ "pushshort 1040\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 41\n"
			+ "getlocal 7\n"
			+ "si32\n"
			+ "getlocal 7\n"
			+ "findproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "swap\n"
			+ "setproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "findpropstrict Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"Fmemset\")\n"
			+ "callpropvoid Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"Fmemset\") 0\n"
			+ "getlocal 7\n"
			+ "pushbyte 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 7\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 7\n"
			+ "pushshort 1024\n"
			+ "getlocal 7\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 43\n"
			+ "getlocal 7\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 11\n"
			+ "pushshort 2064\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 40\n"
			+ "getlocal 7\n"
			+ "si32\n"
			+ "getlocal 7\n"
			+ "findproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "swap\n"
			+ "setproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "findpropstrict Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"Fmemset\")\n"
			+ "callpropvoid Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"Fmemset\") 0\n"
			+ "getlocal 7\n"
			+ "pushbyte 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 7\n"
			+ "pushint 959447040\n"
			+ "getlocal 11\n"
			+ "pushshort 1040\n"
			+ "subtract\n"
			+ "si32\n"
			+ "pushint 33554432\n"
			+ "getlocal 11\n"
			+ "pushshort 1036\n"
			+ "subtract\n"
			+ "si32\n"
			+ "getlocal 17\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 38\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 34\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 34\n"
			+ "getlocal 36\n"
			+ "bitor\n"
			+ "setlocal 36\n"
			+ "getlocal 38\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "setlocal 34\n"
			+ "getlocal 38\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "setlocal 38\n"
			+ "getlocal 34\n"
			+ "getlocal 38\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "getlocal 36\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 11\n"
			+ "pushshort 1032\n"
			+ "subtract\n"
			+ "si32\n"
			+ "getlocal 22\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "getlocal 36\n"
			+ "bitor\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "setlocal 38\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "setlocal 22\n"
			+ "getlocal 38\n"
			+ "getlocal 22\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 36\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 11\n"
			+ "pushshort 1028\n"
			+ "subtract\n"
			+ "si32\n"
			+ "getlocal 44\n"
			+ "li8\n"
			+ "setlocal 18\n"
			+ "getlocal 43\n"
			+ "setlocal 27\n"
			+ "getlocal 18\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs0282\n"
			+ "label\n"
			+ "getlocal 44\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 28\n"
			+ "pushbyte 0\n"
			+ "setlocal 27\n"
			+ "label ofs0242\n"
			+ "getlocal 27\n"
			+ "pushshort 131\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 18\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushbyte 24\n"
			+ "rshift\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 27\n"
			+ "getlocal 28\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 28\n"
			+ "li8\n"
			+ "setlocal 18\n"
			+ "getlocal 22\n"
			+ "setlocal 28\n"
			+ "getlocal 18\n"
			+ "pushbyte 0\n"
			+ "ifne ofs0242\n"
			+ "label\n"
			+ "getlocal 27\n"
			+ "pushint 2147483647\n"
			+ "bitand\n"
			+ "setlocal 27\n"
			+ "label ofs0282\n"
			+ "getlocal 27\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 27\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "bitor\n"
			+ "setlocal 22\n"
			+ "getlocal 27\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "setlocal 36\n"
			+ "getlocal 27\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "setlocal 38\n"
			+ "getlocal 36\n"
			+ "getlocal 38\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 11\n"
			+ "pushshort 1024\n"
			+ "subtract\n"
			+ "si32\n"
			+ "pushbyte 53\n"
			+ "setlocal 18\n"
			+ "pushshort 128\n"
			+ "setlocal 27\n"
			+ "label ofs02d1\n"
			+ "getlocal 43\n"
			+ "pushshort 131\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 18\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushbyte 24\n"
			+ "rshift\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 43\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"L__2E_str3\")\n"
			+ "getlocal 27\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort 129\n"
			+ "add\n"
			+ "li8\n"
			+ "setlocal 18\n"
			+ "getlocal 27\n"
			+ "pushbyte -1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 27\n"
			+ "pushbyte 0\n"
			+ "ifne ofs02d1\n"
			+ "label\n"
			+ "getlocal 43\n"
			+ "pushint 2147483647\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 36\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 36\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 36\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 11\n"
			+ "pushshort 1020\n"
			+ "subtract\n"
			+ "si32\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"_next\")\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 43\n"
			+ "pushbyte 0\n"
			+ "ifne ofs0365\n"
			+ "label\n"
			+ "pushint 123459876\n"
			+ "dup\n"
			+ "setlocal 43\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"_next\")\n"
			+ "si32\n"
			+ "label ofs0365\n"
			+ "getlocal 43\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort -2836\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 43\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "modulo\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushshort 16807\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 18\n"
			+ "pushint 2147483647\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 43\n"
			+ "getlocal 18\n"
			+ "pushbyte 0\n"
			+ "iflt ofs03a6\n"
			+ "getlocal 18\n"
			+ "setlocal 43\n"
			+ "label ofs03a6\n"
			+ "getlocal 43\n"
			+ "pushshort 248\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 6\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "si8\n"
			+ "pushint 123459876\n"
			+ "dup\n"
			+ "setlocal 30\n"
			+ "setlocal 18\n"
			+ "getlocal 43\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs03cf\n"
			+ "getlocal 43\n"
			+ "setlocal 18\n"
			+ "label ofs03cf\n"
			+ "getlocal 18\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort -2836\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 18\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "modulo\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushshort 16807\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 43\n"
			+ "pushint 2147483647\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 27\n"
			+ "getlocal 43\n"
			+ "pushbyte 0\n"
			+ "iflt ofs0410\n"
			+ "getlocal 43\n"
			+ "setlocal 27\n"
			+ "label ofs0410\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 43\n"
			+ "pushbyte 1\n"
			+ "bitor\n"
			+ "setlocal 18\n"
			+ "getlocal 27\n"
			+ "getlocal 18\n"
			+ "si8\n"
			+ "getlocal 30\n"
			+ "setlocal 28\n"
			+ "getlocal 27\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs0434\n"
			+ "getlocal 27\n"
			+ "setlocal 28\n"
			+ "label ofs0434\n"
			+ "getlocal 28\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort -2836\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 28\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "modulo\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushshort 16807\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 27\n"
			+ "pushint 2147483647\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 28\n"
			+ "getlocal 27\n"
			+ "pushbyte 0\n"
			+ "iflt ofs0475\n"
			+ "getlocal 27\n"
			+ "setlocal 28\n"
			+ "label ofs0475\n"
			+ "getlocal 43\n"
			+ "pushbyte 2\n"
			+ "bitor\n"
			+ "setlocal 27\n"
			+ "getlocal 28\n"
			+ "getlocal 27\n"
			+ "si8\n"
			+ "getlocal 30\n"
			+ "setlocal 32\n"
			+ "getlocal 28\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs0492\n"
			+ "getlocal 28\n"
			+ "setlocal 32\n"
			+ "label ofs0492\n"
			+ "getlocal 32\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort -2836\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 32\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "modulo\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushshort 16807\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 28\n"
			+ "pushint 2147483647\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 32\n"
			+ "getlocal 28\n"
			+ "pushbyte 0\n"
			+ "iflt ofs04d3\n"
			+ "getlocal 28\n"
			+ "setlocal 32\n"
			+ "label ofs04d3\n"
			+ "getlocal 43\n"
			+ "pushbyte 3\n"
			+ "bitor\n"
			+ "setlocal 28\n"
			+ "getlocal 32\n"
			+ "getlocal 28\n"
			+ "si8\n"
			+ "getlocal 30\n"
			+ "setlocal 23\n"
			+ "getlocal 32\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs04f0\n"
			+ "getlocal 32\n"
			+ "setlocal 23\n"
			+ "label ofs04f0\n"
			+ "getlocal 23\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort -2836\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 23\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "modulo\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushshort 16807\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 32\n"
			+ "pushint 2147483647\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 23\n"
			+ "getlocal 32\n"
			+ "pushbyte 0\n"
			+ "iflt ofs0531\n"
			+ "getlocal 32\n"
			+ "setlocal 23\n"
			+ "label ofs0531\n"
			+ "getlocal 43\n"
			+ "pushbyte 4\n"
			+ "bitor\n"
			+ "setlocal 32\n"
			+ "getlocal 23\n"
			+ "getlocal 32\n"
			+ "si8\n"
			+ "getlocal 30\n"
			+ "setlocal 24\n"
			+ "getlocal 23\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs054e\n"
			+ "getlocal 23\n"
			+ "setlocal 24\n"
			+ "label ofs054e\n"
			+ "getlocal 24\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort -2836\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 24\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "modulo\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushshort 16807\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 23\n"
			+ "pushint 2147483647\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 24\n"
			+ "getlocal 23\n"
			+ "pushbyte 0\n"
			+ "iflt ofs058f\n"
			+ "getlocal 23\n"
			+ "setlocal 24\n"
			+ "label ofs058f\n"
			+ "getlocal 43\n"
			+ "pushbyte 5\n"
			+ "bitor\n"
			+ "setlocal 23\n"
			+ "getlocal 24\n"
			+ "getlocal 23\n"
			+ "si8\n"
			+ "getlocal 24\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs05a8\n"
			+ "getlocal 24\n"
			+ "setlocal 30\n"
			+ "label ofs05a8\n"
			+ "getlocal 30\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort -2836\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 30\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "modulo\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushshort 16807\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 30\n"
			+ "pushint 2147483647\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 25\n"
			+ "getlocal 30\n"
			+ "pushbyte 0\n"
			+ "iflt ofs05e9\n"
			+ "getlocal 30\n"
			+ "setlocal 25\n"
			+ "label ofs05e9\n"
			+ "getlocal 43\n"
			+ "pushbyte 6\n"
			+ "bitor\n"
			+ "setlocal 26\n"
			+ "getlocal 25\n"
			+ "getlocal 26\n"
			+ "si8\n"
			+ "getlocal 25\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"_next\")\n"
			+ "si32\n"
			+ "getlocal 11\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 20\n"
			+ "pushbyte 4\n"
			+ "bitor\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "getlocal 22\n"
			+ "si32\n"
			+ "pushbyte 0\n"
			+ "getlocal 11\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "si32\n"
			+ "pushbyte 1\n"
			+ "setlocal 19\n"
			+ "pushbyte 7\n"
			+ "setlocal 16\n"
			+ "pushbyte 0\n"
			+ "setlocal 14\n"
			+ "pushbyte 0\n"
			+ "setlocal 15\n"
			+ "pushbyte 0\n"
			+ "setlocal 30\n"
			+ "pushbyte 0\n"
			+ "setlocal 12\n"
			+ "pushbyte 0\n"
			+ "setlocal 13\n"
			+ "pushbyte 0\n"
			+ "setlocal 9\n"
			+ "pushbyte 0\n"
			+ "setlocal 10\n"
			+ "pushbyte 0\n"
			+ "setlocal 6\n"
			+ "pushbyte 0\n"
			+ "setlocal 24\n"
			+ "jump ofs0a09\n"
			+ "label ofs0647\n"
			+ "getlocal 16\n"
			+ "pushbyte 7\n"
			+ "ifgt ofs06c0\n"
			+ "label\n"
			+ "pushint 123459876\n"
			+ "setlocal 8\n"
			+ "getlocal 25\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs0661\n"
			+ "getlocal 25\n"
			+ "setlocal 8\n"
			+ "label ofs0661\n"
			+ "getlocal 8\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushshort -2836\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 8\n"
			+ "convert_u\n"
			+ "pushuint 127773\n"
			+ "modulo\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushshort 16807\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 8\n"
			+ "pushint 2147483647\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 25\n"
			+ "getlocal 8\n"
			+ "pushbyte 0\n"
			+ "iflt ofs06a2\n"
			+ "getlocal 8\n"
			+ "setlocal 25\n"
			+ "label ofs06a2\n"
			+ "getlocal 43\n"
			+ "getlocal 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 25\n"
			+ "getlocal 22\n"
			+ "si8\n"
			+ "getlocal 19\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 19\n"
			+ "getlocal 16\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 16\n"
			+ "label ofs06c0\n"
			+ "getlocal 16\n"
			+ "pushbyte 8\n"
			+ "ifne ofs0a0a\n"
			+ "label\n"
			+ "getlocal 25\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"_next\")\n"
			+ "si32\n"
			+ "getlocal 20\n"
			+ "li8\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li8\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "si8\n"
			+ "getlocal 18\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 18\n"
			+ "si8\n"
			+ "getlocal 27\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 27\n"
			+ "si8\n"
			+ "getlocal 28\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 28\n"
			+ "si8\n"
			+ "getlocal 32\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 32\n"
			+ "si8\n"
			+ "getlocal 23\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 23\n"
			+ "si8\n"
			+ "getlocal 26\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 26\n"
			+ "si8\n"
			+ "getlocal 43\n"
			+ "pushbyte 7\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "si8\n"
			+ "getlocal 32\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 36\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 36\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 36\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 20\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 22\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 16\n"
			+ "pushbyte 16\n"
			+ "setlocal 8\n"
			+ "pushint -1640531527\n"
			+ "setlocal 5\n"
			+ "label ofs07e6\n"
			+ "getlocal 20\n"
			+ "getlocal 5\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 20\n"
			+ "pushbyte 5\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1281895718\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "setlocal 22\n"
			+ "getlocal 20\n"
			+ "pushbyte 4\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1735078436\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 16\n"
			+ "getlocal 5\n"
			+ "getlocal 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 16\n"
			+ "pushbyte 5\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 879325047\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "bitxor\n"
			+ "setlocal 22\n"
			+ "getlocal 16\n"
			+ "pushbyte 4\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1815356193\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 20\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 20\n"
			+ "getlocal 5\n"
			+ "pushint -1640531527\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 5\n"
			+ "getlocal 8\n"
			+ "pushbyte -1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 8\n"
			+ "pushbyte 0\n"
			+ "ifne ofs07e6\n"
			+ "label\n"
			+ "getlocal 16\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 16\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 16\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 16\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 11\n"
			+ "pushshort 2064\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 14\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "dup\n"
			+ "getlocal 22\n"
			+ "si32\n"
			+ "getlocal 20\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 20\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 34\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 34\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 20\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 20\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 31\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 34\n"
			+ "swap\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "getlocal 22\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 24\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 6\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 10\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 9\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 38\n"
			+ "getlocal 13\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 12\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 30\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 15\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 11\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 4\n"
			+ "bitor\n"
			+ "getlocal 32\n"
			+ "li32\n"
			+ "setlocal 13\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li32\n"
			+ "setlocal 24\n"
			+ "getlocal 13\n"
			+ "swap\n"
			+ "si32\n"
			+ "getlocal 24\n"
			+ "getlocal 11\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "si32\n"
			+ "getlocal 13\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 9\n"
			+ "getlocal 13\n"
			+ "pushbyte 16\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 16\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 10\n"
			+ "getlocal 13\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 6\n"
			+ "getlocal 14\n"
			+ "pushbyte -8\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 14\n"
			+ "getlocal 40\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "convert_i\n"
			+ "getlocal 13\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 15\n"
			+ "getlocal 13\n"
			+ "pushbyte 16\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 30\n"
			+ "getlocal 13\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 12\n"
			+ "pushbyte 0\n"
			+ "setlocal 16\n"
			+ "getlocal 40\n"
			+ "setlocal 20\n"
			+ "setlocal 40\n"
			+ "label ofs0a09\n"
			+ "label ofs0a0a\n"
			+ "getlocal 19\n"
			+ "pushbyte 3\n"
			+ "iflt ofs0647\n"
			+ "label\n"
			+ "getlocal 25\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"_next\")\n"
			+ "si32\n"
			+ "getlocal 11\n"
			+ "pushshort 2064\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 40\n"
			+ "getlocal 14\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 5\n"
			+ "pushbyte 0\n"
			+ "getlocal 14\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 29\n"
			+ "pushbyte 24\n"
			+ "setlocal 8\n"
			+ "pushbyte 0\n"
			+ "dup\n"
			+ "setlocal 25\n"
			+ "setlocal 19\n"
			+ "jump ofs0dc3\n"
			+ "label ofs0a41\n"
			+ "getlocal 16\n"
			+ "pushbyte 7\n"
			+ "ifgt ofs0a71\n"
			+ "label\n"
			+ "getlocal 43\n"
			+ "getlocal 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "getlocal 41\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "si8\n"
			+ "getlocal 8\n"
			+ "pushbyte -1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 8\n"
			+ "getlocal 41\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "getlocal 16\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 16\n"
			+ "label ofs0a71\n"
			+ "getlocal 16\n"
			+ "pushbyte 8\n"
			+ "ifne ofs0dd3\n"
			+ "label\n"
			+ "getlocal 20\n"
			+ "li8\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li8\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "si8\n"
			+ "getlocal 18\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 18\n"
			+ "si8\n"
			+ "getlocal 27\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 27\n"
			+ "si8\n"
			+ "getlocal 28\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 28\n"
			+ "si8\n"
			+ "getlocal 32\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 32\n"
			+ "si8\n"
			+ "getlocal 23\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 23\n"
			+ "si8\n"
			+ "getlocal 26\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 26\n"
			+ "si8\n"
			+ "getlocal 43\n"
			+ "pushbyte 7\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "si8\n"
			+ "getlocal 32\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 36\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 36\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 36\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 35\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 22\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 33\n"
			+ "pushbyte 16\n"
			+ "setlocal 20\n"
			+ "pushint -1640531527\n"
			+ "setlocal 16\n"
			+ "label ofs0b91\n"
			+ "getlocal 35\n"
			+ "getlocal 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 35\n"
			+ "pushbyte 5\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1281895718\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "setlocal 22\n"
			+ "getlocal 35\n"
			+ "pushbyte 4\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1735078436\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 33\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 33\n"
			+ "getlocal 16\n"
			+ "getlocal 33\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 33\n"
			+ "pushbyte 5\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 879325047\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "bitxor\n"
			+ "setlocal 22\n"
			+ "getlocal 33\n"
			+ "pushbyte 4\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1815356193\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 35\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 35\n"
			+ "getlocal 16\n"
			+ "pushint -1640531527\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 16\n"
			+ "getlocal 20\n"
			+ "pushbyte -1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 20\n"
			+ "pushbyte 0\n"
			+ "ifne ofs0b91\n"
			+ "label\n"
			+ "getlocal 33\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 33\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 33\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 33\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 29\n"
			+ "getlocal 39\n"
			+ "add\n"
			+ "convert_i\n"
			+ "si32\n"
			+ "getlocal 35\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 35\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 35\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 35\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 37\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 39\n"
			+ "getlocal 29\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 24\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "si8\n"
			+ "getlocal 37\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 6\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 37\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 37\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 10\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 37\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 37\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 9\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 37\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 37\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 13\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 37\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 37\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 12\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 37\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 37\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 30\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 37\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 37\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 15\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 37\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 11\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 4\n"
			+ "bitor\n"
			+ "getlocal 32\n"
			+ "li32\n"
			+ "setlocal 13\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li32\n"
			+ "setlocal 24\n"
			+ "getlocal 13\n"
			+ "swap\n"
			+ "si32\n"
			+ "getlocal 24\n"
			+ "getlocal 11\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "si32\n"
			+ "getlocal 13\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 9\n"
			+ "getlocal 13\n"
			+ "pushbyte 16\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 16\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 10\n"
			+ "getlocal 13\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 6\n"
			+ "getlocal 25\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 25\n"
			+ "getlocal 19\n"
			+ "pushbyte -8\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 19\n"
			+ "getlocal 5\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "convert_i\n"
			+ "getlocal 13\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 15\n"
			+ "getlocal 13\n"
			+ "pushbyte 16\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 30\n"
			+ "getlocal 13\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 12\n"
			+ "pushbyte 0\n"
			+ "setlocal 16\n"
			+ "getlocal 5\n"
			+ "setlocal 20\n"
			+ "setlocal 5\n"
			+ "label ofs0dc3\n"
			+ "getlocal 40\n"
			+ "getlocal 25\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 39\n"
			+ "getlocal 29\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 37\n"
			+ "label ofs0dd3\n"
			+ "getlocal 8\n"
			+ "pushbyte 0\n"
			+ "ifne ofs0a41\n"
			+ "label\n"
			+ "getlocal 39\n"
			+ "getlocal 14\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 19\n"
			+ "getlocal 14\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 25\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "pushbyte 1\n"
			+ "setlocal 14\n"
			+ "jump ofs116f\n"
			+ "label ofs0dfc\n"
			+ "getlocal 16\n"
			+ "pushbyte 7\n"
			+ "ifgt ofs0e20\n"
			+ "label\n"
			+ "getlocal 43\n"
			+ "getlocal 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "pushbyte 0\n"
			+ "swap\n"
			+ "si8\n"
			+ "getlocal 14\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 14\n"
			+ "getlocal 16\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 16\n"
			+ "label ofs0e20\n"
			+ "getlocal 16\n"
			+ "pushbyte 8\n"
			+ "ifne ofs1170\n"
			+ "label\n"
			+ "getlocal 20\n"
			+ "li8\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li8\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "si8\n"
			+ "getlocal 18\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 18\n"
			+ "si8\n"
			+ "getlocal 27\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 27\n"
			+ "si8\n"
			+ "getlocal 28\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 28\n"
			+ "si8\n"
			+ "getlocal 32\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 32\n"
			+ "si8\n"
			+ "getlocal 23\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 23\n"
			+ "si8\n"
			+ "getlocal 26\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 26\n"
			+ "si8\n"
			+ "getlocal 43\n"
			+ "pushbyte 7\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "li8\n"
			+ "getlocal 20\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "si8\n"
			+ "getlocal 32\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 36\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 36\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 36\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 16\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 22\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 25\n"
			+ "pushbyte 16\n"
			+ "setlocal 20\n"
			+ "pushint -1640531527\n"
			+ "setlocal 8\n"
			+ "label ofs0f40\n"
			+ "getlocal 16\n"
			+ "getlocal 8\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 16\n"
			+ "pushbyte 5\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1281895718\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "setlocal 22\n"
			+ "getlocal 16\n"
			+ "pushbyte 4\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1735078436\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 25\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 25\n"
			+ "getlocal 8\n"
			+ "getlocal 25\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 25\n"
			+ "pushbyte 5\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 879325047\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "bitxor\n"
			+ "setlocal 22\n"
			+ "getlocal 25\n"
			+ "pushbyte 4\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 1815356193\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "getlocal 36\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 16\n"
			+ "getlocal 8\n"
			+ "pushint -1640531527\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 8\n"
			+ "getlocal 20\n"
			+ "pushbyte -1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 20\n"
			+ "pushbyte 0\n"
			+ "ifne ofs0f40\n"
			+ "label\n"
			+ "getlocal 25\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 25\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 25\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 25\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 40\n"
			+ "getlocal 41\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 16\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 16\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushint 65280\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "getlocal 16\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 16\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 34\n"
			+ "pushint 16711680\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "si32\n"
			+ "getlocal 22\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 24\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 6\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 10\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 9\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 5\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 13\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 6\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 12\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 7\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 30\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 9\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 15\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "pushbyte 9\n"
			+ "add\n"
			+ "si8\n"
			+ "getlocal 11\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 4\n"
			+ "bitor\n"
			+ "getlocal 32\n"
			+ "li32\n"
			+ "setlocal 13\n"
			+ "getlocal 11\n"
			+ "pushbyte 8\n"
			+ "subtract\n"
			+ "li32\n"
			+ "setlocal 24\n"
			+ "getlocal 13\n"
			+ "swap\n"
			+ "si32\n"
			+ "getlocal 24\n"
			+ "getlocal 11\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "si32\n"
			+ "getlocal 13\n"
			+ "pushbyte 8\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 9\n"
			+ "getlocal 13\n"
			+ "pushbyte 16\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 16\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 10\n"
			+ "getlocal 13\n"
			+ "pushbyte 24\n"
			+ "lshift\n"
			+ "getlocal 24\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "bitor\n"
			+ "setlocal 6\n"
			+ "getlocal 41\n"
			+ "pushbyte -8\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "getlocal 19\n"
			+ "pushbyte 8\n"
			+ "add\n"
			+ "convert_i\n"
			+ "getlocal 13\n"
			+ "pushbyte 24\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 15\n"
			+ "getlocal 13\n"
			+ "pushbyte 16\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 30\n"
			+ "getlocal 13\n"
			+ "pushbyte 8\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 12\n"
			+ "pushbyte 0\n"
			+ "setlocal 16\n"
			+ "getlocal 19\n"
			+ "setlocal 20\n"
			+ "setlocal 19\n"
			+ "label ofs116f\n"
			+ "label ofs1170\n"
			+ "getlocal 14\n"
			+ "pushbyte 8\n"
			+ "iflt ofs0dfc\n"
			+ "label\n"
			+ "pushbyte 2\n"
			+ "getlocal 41\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 28\n"
			+ "pushbyte 0\n"
			+ "iflt ofs13ac\n"
			+ "label\n"
			+ "getlocal 28\n"
			+ "pushbyte 3\n"
			+ "divide\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 27\n"
			+ "pushbyte 3\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "setlocal 18\n"
			+ "pushbyte 1\n"
			+ "setlocal 43\n"
			+ "getlocal 18\n"
			+ "getlocal 28\n"
			+ "iflt ofs11a9\n"
			+ "pushbyte 0\n"
			+ "setlocal 43\n"
			+ "label ofs11a9\n"
			+ "getlocal 43\n"
			+ "pushbyte 1\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 27\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 2\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 43\n"
			+ "pushshort 1024\n"
			+ "ifgt ofs11fd\n"
			+ "label\n"
			+ "pushbyte 0\n"
			+ "setlocal 32\n"
			+ "getlocal 28\n"
			+ "pushbyte 3\n"
			+ "iflt ofs12cb\n"
			+ "label\n"
			+ "getlocal 27\n"
			+ "setlocal 32\n"
			+ "getlocal 27\n"
			+ "pushbyte 1\n"
			+ "ifgt ofs11e4\n"
			+ "pushbyte 1\n"
			+ "setlocal 32\n"
			+ "label ofs11e4\n"
			+ "getlocal 40\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 23\n"
			+ "getlocal 42\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 30\n"
			+ "getlocal 32\n"
			+ "setlocal 24\n"
			+ "jump ofs120b\n"
			+ "label ofs11fd\n"
			+ "pushbyte 0\n"
			+ "getlocal 11\n"
			+ "pushshort 3088\n"
			+ "subtract\n"
			+ "si8\n"
			+ "jump ofs13ac\n"
			+ "label ofs120b\n"
			+ "getlocal 23\n"
			+ "pushbyte 2\n"
			+ "subtract\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 2\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "setlocal 36\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"__ZZ28convertHexDataToBase64StringE10base64Char\")\n"
			+ "getlocal 36\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 30\n"
			+ "pushbyte 3\n"
			+ "subtract\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 4\n"
			+ "lshift\n"
			+ "setlocal 38\n"
			+ "getlocal 23\n"
			+ "decrement\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 4\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 38\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushbyte 63\n"
			+ "bitand\n"
			+ "setlocal 36\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"__ZZ28convertHexDataToBase64StringE10base64Char\")\n"
			+ "getlocal 36\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 30\n"
			+ "pushbyte 2\n"
			+ "subtract\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 2\n"
			+ "lshift\n"
			+ "setlocal 38\n"
			+ "getlocal 23\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 6\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 38\n"
			+ "bitor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushbyte 63\n"
			+ "bitand\n"
			+ "setlocal 36\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"__ZZ28convertHexDataToBase64StringE10base64Char\")\n"
			+ "getlocal 36\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 30\n"
			+ "decrement\n"
			+ "si8\n"
			+ "getlocal 22\n"
			+ "pushbyte 63\n"
			+ "bitand\n"
			+ "setlocal 22\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"__ZZ28convertHexDataToBase64StringE10base64Char\")\n"
			+ "getlocal 22\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 30\n"
			+ "si8\n"
			+ "getlocal 23\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 23\n"
			+ "getlocal 30\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 30\n"
			+ "getlocal 24\n"
			+ "pushbyte -1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 24\n"
			+ "pushbyte 0\n"
			+ "ifne ofs120b\n"
			+ "label ofs12cb\n"
			+ "getlocal 18\n"
			+ "getlocal 28\n"
			+ "ifge ofs139e\n"
			+ "label\n"
			+ "getlocal 27\n"
			+ "pushbyte -3\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "getlocal 32\n"
			+ "pushbyte 2\n"
			+ "lshift\n"
			+ "setlocal 18\n"
			+ "getlocal 42\n"
			+ "getlocal 18\n"
			+ "add\n"
			+ "convert_i\n"
			+ "getlocal 32\n"
			+ "pushbyte 3\n"
			+ "multiply\n"
			+ "convert_i\n"
			+ "getlocal 40\n"
			+ "swap\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 28\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "pushbyte 2\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"__ZZ28convertHexDataToBase64StringE10base64Char\")\n"
			+ "swap\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 34\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 34\n"
			+ "swap\n"
			+ "si8\n"
			+ "getlocal 38\n"
			+ "pushbyte 4\n"
			+ "lshift\n"
			+ "setlocal 40\n"
			+ "getlocal 18\n"
			+ "pushbyte 1\n"
			+ "bitor\n"
			+ "setlocal 27\n"
			+ "getlocal 41\n"
			+ "ifne ofs1372\n"
			+ "label\n"
			+ "getlocal 42\n"
			+ "getlocal 27\n"
			+ "add\n"
			+ "convert_i\n"
			+ "getlocal 28\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 4\n"
			+ "urshift\n"
			+ "convert_i\n"
			+ "getlocal 40\n"
			+ "pushbyte 48\n"
			+ "bitand\n"
			+ "bitor\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"__ZZ28convertHexDataToBase64StringE10base64Char\")\n"
			+ "swap\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 38\n"
			+ "swap\n"
			+ "si8\n"
			+ "getlocal 18\n"
			+ "pushbyte 2\n"
			+ "bitor\n"
			+ "getlocal 42\n"
			+ "swap\n"
			+ "add\n"
			+ "convert_i\n"
			+ "getlocal 22\n"
			+ "pushbyte 2\n"
			+ "lshift\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 60\n"
			+ "bitand\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"__ZZ28convertHexDataToBase64StringE10base64Char\")\n"
			+ "swap\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "swap\n"
			+ "si8\n"
			+ "jump ofs1395\n"
			+ "label ofs1372\n"
			+ "getlocal 42\n"
			+ "getlocal 27\n"
			+ "add\n"
			+ "convert_i\n"
			+ "getlocal 40\n"
			+ "pushbyte 48\n"
			+ "bitand\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"__ZZ28convertHexDataToBase64StringE10base64Char\")\n"
			+ "swap\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "swap\n"
			+ "si8\n"
			+ "getlocal 43\n"
			+ "pushbyte -1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 43\n"
			+ "label ofs1395\n"
			+ "getlocal 43\n"
			+ "pushbyte -1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 43\n"
			+ "label ofs139e\n"
			+ "getlocal 42\n"
			+ "getlocal 43\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "getlocal 22\n"
			+ "si8\n"
			+ "label ofs13ac\n"
			+ "getlocal 42\n"
			+ "pushbyte -4\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 43\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint -16843009\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 36\n"
			+ "pushint -2139062144\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint -2139062144\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs1412\n"
			+ "label\n"
			+ "getlocal 43\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 18\n"
			+ "pushbyte 0\n"
			+ "setlocal 41\n"
			+ "jump ofs1400\n"
			+ "label ofs13ea\n"
			+ "getlocal 27\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs14d8\n"
			+ "label\n"
			+ "getlocal 41\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "label ofs1400\n"
			+ "getlocal 42\n"
			+ "getlocal 41\n"
			+ "add\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 27\n"
			+ "convert_u\n"
			+ "getlocal 18\n"
			+ "convert_u\n"
			+ "iflt ofs13ea\n"
			+ "label ofs1412\n"
			+ "getlocal 43\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "label ofs141b\n"
			+ "getlocal 41\n"
			+ "li32\n"
			+ "dup\n"
			+ "setlocal 43\n"
			+ "pushint -16843009\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 22\n"
			+ "getlocal 43\n"
			+ "pushint -2139062144\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "pushint -2139062144\n"
			+ "bitxor\n"
			+ "dup\n"
			+ "setlocal 36\n"
			+ "getlocal 22\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs14cb\n"
			+ "label\n"
			+ "getlocal 43\n"
			+ "pushshort 255\n"
			+ "bitand\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "ifne ofs145f\n"
			+ "label\n"
			+ "getlocal 41\n"
			+ "getlocal 42\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "jump ofs14d8\n"
			+ "label ofs145f\n"
			+ "getlocal 41\n"
			+ "pushbyte 1\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "ifne ofs1483\n"
			+ "label\n"
			+ "pushbyte 1\n"
			+ "getlocal 42\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 41\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "jump ofs14d8\n"
			+ "label ofs1483\n"
			+ "getlocal 41\n"
			+ "pushbyte 2\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "ifne ofs14a7\n"
			+ "label\n"
			+ "pushbyte 2\n"
			+ "getlocal 42\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 41\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "jump ofs14d8\n"
			+ "label ofs14a7\n"
			+ "getlocal 41\n"
			+ "pushbyte 3\n"
			+ "add\n"
			+ "li8\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "pushbyte 0\n"
			+ "ifne ofs14cb\n"
			+ "label\n"
			+ "pushbyte 3\n"
			+ "getlocal 42\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "dup\n"
			+ "setlocal 22\n"
			+ "getlocal 41\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "jump ofs14d8\n"
			+ "label ofs14cb\n"
			+ "getlocal 41\n"
			+ "pushbyte 4\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 41\n"
			+ "jump ofs141b\n"
			+ "label ofs14d8\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"CModule\")\n"
			+ "getlocal 42\n"
			+ "getlocal 41\n"
			+ "callproperty Qname(PackageNamespace(\"\"),\"readString\") 2\n"
			+ "coerce_s\n"
			+ "setlocal 4\n"
			+ "getlocal 44\n"
			+ "pushbyte 0\n"
			+ "ifeq ofs1514\n"
			+ "label\n"
			+ "getlocal 7\n"
			+ "pushbyte 16\n"
			+ "subtract\n"
			+ "convert_i\n"
			+ "setlocal 7\n"
			+ "getlocal 44\n"
			+ "getlocal 7\n"
			+ "si32\n"
			+ "getlocal 7\n"
			+ "findproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "swap\n"
			+ "setproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "findpropstrict Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"F_idalloc\")\n"
			+ "callpropvoid Qname(PackageNamespace(\"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043\"),\"F_idalloc\") 0\n"
			+ "getlocal 7\n"
			+ "pushbyte 16\n"
			+ "add\n"
			+ "convert_i\n"
			+ "setlocal 7\n"
			+ "label ofs1514\n"
			+ "getlocal 4\n"
			+ "setlocal 21\n"
			+ "getlocal 11\n"
			+ "dup\n"
			+ "setlocal 7\n"
			+ "findproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "swap\n"
			+ "setproperty Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "getlocal 21\n" + "returnvalue\n";
	static String src_of_fmemset = "method\n"
			+ "name Fmemset\n"
			+ "returns Qname(PackageNamespace(\"\"),\"void\")\n"
			+ "\n"
			+ "body\n"
			+ "maxstack 5\n"
			+ "localcount 5\n"
			+ "initscopedepth 0\n"
			+ "maxscopedepth 2\n"
			+ "\n"
			+ "code\n"
			+ "getlocal_0\n"
			+ "dup\n"
			+ "pushscope\n"
			+ "pushscope\n"
			+ "getlex Qname(PackageNamespace(\"com.tencent.utils.flascc\"),\"ESP\")\n"
			+ "convert_i\n" + "setlocal 1\n" + "getlocal_1\n" + "li32\n"
			+ "setlocal 4\n" + "getlocal_1\n" + "pushbyte 4\n" + "add\n"
			+ "li32\n" + "setlocal 2\n" + "getlocal_1\n" + "pushbyte 8\n"
			+ "add\n" + "li32\n" + "setlocal 3\n" + "getlocal_2\n"
			+ "iftrue ofs003d\n" + "jump ofs0036\n" + "label ofs0022\n"
			+ "pushbyte 0\n" + "getlocal 4\n" + "sf64\n" + "getlocal 4\n"
			+ "pushbyte 8\n" + "add\n" + "convert_i\n" + "setlocal 4\n"
			+ "getlocal_3\n" + "pushbyte 8\n" + "subtract\n" + "convert_i\n"
			+ "setlocal 3\n" + "label ofs0036\n" + "getlocal_3\n"
			+ "pushbyte 8\n" + "ifge ofs0022\n" + "label ofs003d\n"
			+ "jump ofs004a\n" + "label ofs0041\n" + "getlocal_2\n"
			+ "getlocal 4\n" + "si8\n" + "inclocal_i 4\n" + "declocal_i 3\n"
			+ "label ofs004a\n" + "getlocal_3\n" + "iftrue ofs0041\n"
			+ "returnvoid\n";

	private static Function getFunction(String mysrc) {
		InputStream input = new ByteArrayInputStream(
				mysrc.getBytes(StandardCharsets.UTF_8));
		FunctionData f = null;
		try {
			f = Parser.parse(input);
			// System.out.println(f.toString());
		} catch (ParseException e) {
			e.printStackTrace();
			System.exit(1);
		}
		return new Function(f);
	}

	private static Function getCCCFunction() {
		return getFunction(src);
	}

	private static Function getFmemsetFunction() {
		return getFunction(src_of_fmemset);
	}

	static byte[] getFileData(String name) throws IOException {
		ClassLoader cloader = Thread.currentThread().getContextClassLoader();
		InputStream in = cloader.getResourceAsStream(name);
		LinkedList<byte[]> list = new LinkedList<byte[]>();
		int read_bytes_count = 0;
		try {
			while (true) {
				byte[] buffer = new byte[1024];
				int read_bytes = in.read(buffer);
				if (read_bytes == -1)
					break;
				read_bytes_count += read_bytes;
				list.add(buffer);
			}
		} finally {
			if (in != null)
				in.close();
		}
		byte[] ret = new byte[read_bytes_count];
		int copyed = 0;
		for (byte[] buffer : list) {
			System.arraycopy(buffer, 0, ret, copyed,
					(ret.length - copyed) < buffer.length ? ret.length - copyed
							: buffer.length);
			copyed += buffer.length;
		}
		return ret;
	}

	static byte[] getROData() throws IOException {
		return getFileData("rodata");
	}

	static byte[] getData() throws IOException {
		return getFileData("data");
	}

	static byte[] getROStrData() throws IOException {
		return getFileData("rodata_str");
	}

	public static void main(String[] args) {
		Function f = getCCCFunction();
		final AppDomain appDom = new AppDomain();
		appDom.setGlobal(new QName("com.tencent.utils.flascc", "ESP"), appDom
				.allocate(40960).add(40960));
		final Module CModule = new Module(new QName("com.tencent.utils.flascc",
				"CModule"));
		CModule.set(new QName("", "mallocString"), new NativeFunction() {

			@Override
			public Object call(Object receiver, Object[] params) {
				if (receiver != CModule)
					throw new IllegalStateException("receiver must be CModule");
				String s = (String) params[0];
				byte[] b = s.getBytes(StandardCharsets.UTF_8);
				return appDom.allocateFromBytes(b);
			}
		});
		CModule.set(new QName("", "readString"), new NativeFunction() {

			@Override
			public Object call(Object receiver, Object[] params) {
				if (receiver != CModule)
					throw new IllegalStateException("receiver must be CModule");
				if (params.length != 2)
					throw new IllegalArgumentException(
							"needs extractly 2 arguments");
				DomainBuffer ptr = (DomainBuffer) params[0];
				DomainBuffer len = (DomainBuffer) params[1];
				if (!ptr.isCompatible(len))
					throw new IllegalStateException("len should always be compatible with ptr");
				System.err.println(String.format("ptr.getOffset() = %d, ptr.getBuffer().length() = %d, len.getOffset() = %d, len.getBuffer().length() = %d", ptr.getOffset(), ptr.getBuffer().length, len.getOffset(), len.getBuffer().length));
				ByteBuffer buffer_of_string = ByteBuffer.wrap(ptr.getBuffer(),
						ptr.getOffset(), len.getOffset());
				return StandardCharsets.UTF_8.decode(buffer_of_string)
						.toString();
			}
		});
		;
		appDom.setGlobal(CModule.getName(), CModule);
		appDom.setGlobal(new QName("com.tencent.utils.flascc", "Fmemset"),
				getFmemsetFunction());
		Interpretor interpretor = new Interpretor(appDom);
		// set up ro data here
		try {
			byte[] rodata = getROData();
			DomainBuffer offset = appDom.allocateFromBytes(rodata);
			appDom.setGlobal(
					new QName(
							"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043",
							"L__2E_str3"), offset.add(144));
		} catch (IOException e) {
			throw new IllegalStateException("fails to set up ro data", e);
		}
		try {
			byte[] data = getData();
			DomainBuffer offset = appDom.allocateFromBytes(data);
			appDom.setGlobal(
					new QName(
							"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043",
							"_next"), offset.add(120));
		} catch (IOException e) {
			throw new IllegalStateException("fails to set up ro data", e);
		}
		try {
			byte[] data = getROStrData();
			DomainBuffer offset = appDom.allocateFromBytes(data);
			appDom.setGlobal(
					new QName(
							"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043",
							"__ZZ28convertHexDataToBase64StringE10base64Char"),
					offset.add(0));
		} catch (IOException e) {
			throw new IllegalStateException("fails to set up ro data", e);
		}
		appDom.setGlobal(
				new QName(
						"com.tencent.utils.flascc__3A__5C_tools_5C_Crossbridge_1_2E_0_2E_1_5C_cygwin_5C_tmp_5C_cc5XyE1n_2E_lto_2E_bc_3A_88a86364_2D_2ed8_2D_4437_2D_97b8_2D_85f87616a043",
						"F_idalloc"), new NativeFunction() {

					@Override
					public Object call(Object receiver, Object[] params) {
						return null;
					}
				});
		Object ret = null;
		if (args.length != 3)
			ret = interpretor.callGlobalFunction(f, new Object[] { 11,
					"3.2.18.278", 0x54213260 });
		else {
			Integer p0 = Integer.valueOf(args[0]);
			String p1 = args[1];
			Integer p2 = Integer.valueOf(args[2]);
			ret = interpretor
					.callGlobalFunction(f, new Object[] { p0, p1, p2 });
		}
		System.out.println("ret = " + ret.toString());
	}

}
